/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-01-14 12:27:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.axis2_002dweb;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.axis2.Constants;
import org.apache.axis2.context.ConfigurationContext;
import org.apache.axis2.context.ServiceContext;
import org.apache.axis2.context.ServiceGroupContext;
import org.apache.axis2.deployment.util.PhasesInfo;
import org.apache.axis2.description.AxisModule;
import org.apache.axis2.description.AxisOperation;
import org.apache.axis2.description.AxisService;
import org.apache.axis2.description.AxisServiceGroup;
import org.apache.axis2.description.Parameter;
import org.apache.axis2.engine.AxisConfiguration;
import org.apache.axis2.engine.Handler;
import org.apache.axis2.engine.Phase;
import org.apache.axis2.util.JavaUtils;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Iterator;

public final class LeftFrame_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.axis2.deployment.util.PhasesInfo");
    _jspx_imports_classes.add("org.apache.axis2.description.Parameter");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("org.apache.axis2.context.ConfigurationContext");
    _jspx_imports_classes.add("org.apache.axis2.context.ServiceGroupContext");
    _jspx_imports_classes.add("java.util.Enumeration");
    _jspx_imports_classes.add("org.apache.axis2.context.ServiceContext");
    _jspx_imports_classes.add("org.apache.axis2.engine.AxisConfiguration");
    _jspx_imports_classes.add("org.apache.axis2.Constants");
    _jspx_imports_classes.add("java.util.Collection");
    _jspx_imports_classes.add("org.apache.axis2.engine.Phase");
    _jspx_imports_classes.add("org.apache.axis2.engine.Handler");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("org.apache.axis2.description.AxisService");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("org.apache.axis2.description.AxisModule");
    _jspx_imports_classes.add("org.apache.axis2.description.AxisServiceGroup");
    _jspx_imports_classes.add("org.apache.axis2.description.AxisOperation");
    _jspx_imports_classes.add("org.apache.axis2.util.JavaUtils");
    _jspx_imports_classes.add("java.util.Hashtable");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" style=\"border-right:1px solid #CCCCCC;\">\r\n");
      out.write("    <tr>\r\n");
      out.write("     <td colspan=\"2\" >\r\n");
      out.write("       <b>Tools </b>\r\n");
      out.write("     </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("       <td>\r\n");
      out.write("       &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("       </td>\r\n");
      out.write("       <td>\r\n");
      out.write("         <a href=\"axis2-admin/upload\">Upload Service</a>\r\n");
      out.write("       </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("<tr>\r\n");
      out.write("     <td colspan=\"2\" >\r\n");
      out.write("      <b><nobr>System Components&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</nobr></b>\r\n");
      out.write("     </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("       &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("    </td>\r\n");
      out.write("    <td >\r\n");
      out.write("      <a href=\"axis2-admin/listService\">Available Services</a>\r\n");
      out.write("    </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("       &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("    </td>\r\n");
      out.write("    <td >\r\n");
      out.write("      <a href=\"axis2-admin/listServiceGroups\">Available Service Groups</a>\r\n");
      out.write("    </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("       &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("    </td>\r\n");
      out.write("    <td >\r\n");
      out.write("      <a href=\"axis2-admin/listModules\">Available Modules</a>\r\n");
      out.write("    </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("       &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <a href=\"axis2-admin/globalModules\">Globally Engaged Modules</a>\r\n");
      out.write("    </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("       &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("    </td>\r\n");
      out.write("    <td >\r\n");
      out.write("      <a href=\"axis2-admin/listPhases\">Available Phases</a>\r\n");
      out.write("    </td>\r\n");
      out.write(" </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("     <td colspan=\"2\" >\r\n");
      out.write("       <b>Execution Chains</b>\r\n");
      out.write("     </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("       <td>\r\n");
      out.write("       &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("       </td>\r\n");
      out.write("       <td>\r\n");
      out.write("         <a href=\"axis2-admin/viewGlobalHandlers\">Global Chains</a>\r\n");
      out.write("       </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("       <td>\r\n");
      out.write("       &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("       </td>\r\n");
      out.write("       <td>\r\n");
      out.write("         <a href=\"axis2-admin/selectService\">Operation Specific Chains</a>\r\n");
      out.write("       </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("     <td colspan=\"2\" >\r\n");
      out.write("       <b>Engage Module</b>\r\n");
      out.write("     </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("       <td>\r\n");
      out.write("        &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("       </td>\r\n");
      out.write("       <td>\r\n");
      out.write("         <a href=\"axis2-admin/engagingglobally\">For all Services</a>\r\n");
      out.write("       </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("        <td>\r\n");
      out.write("         &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("          <a href=\"axis2-admin/engageToServiceGroup\">For a Service Group</a>\r\n");
      out.write("        </td>\r\n");
      out.write("     </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("       <td>\r\n");
      out.write("       &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("       </td>\r\n");
      out.write("       <td>\r\n");
      out.write("         <a href=\"axis2-admin/engageToService\">For a Service</a>\r\n");
      out.write("       </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td>\r\n");
      out.write("       &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("       </td>\r\n");
      out.write("       <td>\r\n");
      out.write("         <a href=\"axis2-admin/listOperation\">For an Operation</a>\r\n");
      out.write("       </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("     <td colspan=\"2\" >\r\n");
      out.write("       <b>Services</b>\r\n");
      out.write("     </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("       <td>\r\n");
      out.write("       &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("       </td>\r\n");
      out.write("       <td>\r\n");
      out.write("         <a href=\"axis2-admin/deactivateService\">Deactivate Service</a>\r\n");
      out.write("       </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("       <td>\r\n");
      out.write("       &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("       </td>\r\n");
      out.write("       <td>\r\n");
      out.write("         <a href=\"axis2-admin/activateService\">Activate Service</a>\r\n");
      out.write("       </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("       <td>\r\n");
      out.write("       &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("       </td>\r\n");
      out.write("       <td>\r\n");
      out.write("         <a href=\"axis2-admin/selectServiceParaEdit\">Edit Parameters</a>\r\n");
      out.write("       </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("     <td colspan=\"2\" >\r\n");
      out.write("       <b>Contexts</b>\r\n");
      out.write("     </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("       <td>\r\n");
      out.write("       &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("       </td>\r\n");
      out.write("       <td>\r\n");
      out.write("         <a href=\"axis2-admin/listContexts\">View Hierarchy</a>\r\n");
      out.write("       </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
